[platformio]
default_envs = x3
extra_configs = platformio.local.ini

[env:x3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.flash_size = 16MB
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++2a
  -fno-exceptions
  -DFREEINK_DEVICE_X3=1
  -DFREEINK_BOOK_SMALL=1
  -DEINK_DISPLAY_SINGLE_BUFFER_MODE=1
  -DDESTRUCTOR_CLOSES_FILE=1
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  BoardConfig=symlink://third_party/freeink-sdk/libs/hardware/BoardConfig
  EInkDisplay=symlink://third_party/freeink-sdk/libs/display/FreeInkDisplay
  InputManager=symlink://third_party/freeink-sdk/libs/hardware/InputManager
  SDCardManager=symlink://third_party/freeink-sdk/libs/hardware/SDCardManager
  XteinkDetect=symlink://third_party/freeink-sdk/libs/hardware/XteinkDetect
  PowerManager=symlink://third_party/freeink-sdk/libs/hardware/PowerManager
  FreeInkUI=symlink://third_party/freeink-sdk/libs/ui/FreeInkUI
  FreeInkFont=symlink://third_party/freeink-sdk/libs/font/FreeInkFont
  FreeInkBook=symlink://third_party/freeink-sdk/libs/book/FreeInkBook
  PagePet=symlink://third_party/pagepet
